export const homeData = {
  home_main: {
    top_ua: 'Засновано',
    top_ru: 'основаны',
    top_en: 'founded',
    title_ua: 'Ricchezza \nСтудія Дизайну \nМеблів',
    title_ru: 'Ricchezza \nСтудия Дизайна \nМебели',
    title_en: 'Ricchezza \nfurniture design \nstudio',
    description_ua: 'Завдяки індивідуальному підходу, \nми створюємо меблі любої складності, \nта на любий смак',
    description_ru: 'Благодаря индивидуальному подходу, \nмы создаем мебель любой сложности, \nи на любой вкус',
    description_en: 'Thanks to an individual approach, \nnwe create furniture of any complexity, \nand for every taste',
  },
  home_order: {
    description_ua: 'Меблі на замовлення',
    description_ru: 'Мебель на заказ',
    description_en: 'furniture for order',
    title_ua: 'НАШІ МАЙСТРИ СТВОРЮЮТЬ \nДЛЯ ВАС СПРАВЖНІ ШЕДЕВРИ',
    title_ru: 'наши мастера создают \nдля вас настоящие шедевры',
    title_en: 'OUR MASTERS CREATE \nTRUE MASTERPIECES FOR YOU',
    button_ua: 'Замовити меблі',
    button_ru: 'Заказать мель',
    button_en: 'order furniture',
    },
  home_benefits: {
    description_ua: 'Чому ми',
    description_ru: 'почему мы',
    description_en: 'furniture for order',
    title_ua: 'Ми завжди працюємо над \nпідвищенням якості наших \nмеблів та сервісу',
    title_ru: 'Мы всегда работаем над \nповышением качества наших \nмебели и сервиса',
    title_en: 'We are always working to \nimprove the quality of our \nfurniture and service',
    first_ua: 'Вишуканість дизайну \nнаших меблів',
    first_ru: 'Изысканность дизайна \nнашей мебели',
    first_en: 'oThe sophistication of \nour furniture design',
    second_ua: 'Висока якість та надійність \nусіх виробів',
    second_ru: 'Высокое качество и надежность \nвсех изделий',
    second_en: 'High quality and reliability \nof all products',
    third_ua: 'Екологічність та \nнатуральність матеріалів',
    third_ru: 'Экологичность и \nнатуральность материалов',
    third_en: 'Environmental friendliness and \nnaturalness of materials',
    fourth_ua: 'Доставка готової \nпродукції по всій країні',
    fourth_ru: 'доставка готовой \nпродукции по всей стране',
    fourth_en: 'delivery of finished \nproducts throughout the country',
  },
  home_catalog: {
    description_ua: 'Каталог готових меблів',
    description_ru: 'Каталог готовой мебели',
    description_en: 'Finished furniture catalog',
    title_ua:
      'В нашому каталозі ви \nзможете обрати готві меблі на \nрізноманітний смак',
    title_ru:
      'В нашем каталоге вы \nсможете выбрать готовую мебель на \nразнообразный вкус.',
    title_en:
      'In our catalog you \ncan choose ready-made furniture for \ndifferent tastes',
    button_ua: 'Перейти в каталог',
    button_ru: 'Перейти в каталог',
    button_en: 'go to catalog',
    catalog: {
      title_ua: 'Стіл “Futuristic”',
      title_ru: 'Стол “Futuristic”',
      title_en: 'Table "Futuristic"',
      price: '12 000',
      link: '/',
    },
  },
  home_about: {
    description_ua: 'Про студію “Ricchezza”',
    description_ru: 'О студии "Ricchezza"',
    description_en: 'About Ricchezza Studio',
    title_ua: 'Студія “Ricchezza” виробник \nмеблів Європейського рівня \nта якості',
    title_ru: 'Студия "Ricchezza" производитель \nмебели Европейского уровня \nи качества',
    title_en: 'Ricchezza Studio is a manufacturer of \nfurniture of European level \nand quality',
    titleAbout_ua: 'Хто ми:',
    titleAbout_ru: 'Кто мы:',
    titleAbout_en: 'Who we are:',
    descriptionAbout_ua: 'Нец ет ерос тота яуодси, ферри иусто еум ин, инани иудицабит \nяуаерендум хас ан. Лорем ипсум долор сит амет, доценди пондерум \nид при, проприае пхаедрум вих еа. Сед деленити сенсибус \nадверсариум еу, еи оратио аудире хис, еос принципес сцрипторем ад.',
    descriptionAbout_ru: 'Нец эт ерос тота яуодсы, ферри иусто еум ин, инаны иудицабит \nяуаэрендум хас ан. Лорем ипсум долор сит амет, доценды пондерум \nид при, проприает пхаэдрум их еа. Сед разделить сенсибус \nадверсариум еу, еи оратио аудире хис, еос принципес сцриптором ад.',
    descriptionAbout_en: 'Net et eros tota yauodsi, ferri iusto eum in, inani iuditsabit \nyawaerendum has an. Lorem ipsum dolor sit amet, docendi ponderum \nid pri, propriee phaedrum vih ea. Sed deleniti sensibus \nadversarium eu, ei oratio audire his, eos principes scriptorem ad.',
    titleHistory_ua: 'Наша історія:',
    titleHistory_ru: 'Наша история:',
    titleHistory_en: 'Our story:',
    descriptionHistory_ua: 'Нец ет ерос тота яуодси, ферри иусто еум ин, инани иудицабит \nяуаерендум хас ан. Лорем ипсум долор сит амет, доценди пондерум \nид при, проприае пхаедрум вих еа. Сед деленити сенсибус \nадверсариум еу, еи оратио аудире хис, еос принципес сцрипторем ад.',
    descriptionHistory_ru: 'Нец эт ерос тота яуодсы, ферри иусто еум ин, инаны иудицабит \nяуаэрендум хас ан. Лорем ипсум долор сит амет, доценды пондерум \nид при, проприает пхаэдрум их еа. Сед разделить сенсибус \nадверсариум еу, еи оратио аудире хис, еос принципес сцриптором ад.',
    descriptionHistory_en: 'Net et eros tota yauodsi, ferri iusto eum in, inani iuditsabit \nyawaerendum has an. Lorem ipsum dolor sit amet, docendi ponderum \nid pri, propriee phaedrum vih ea. Sed deleniti sensibus \nadversarium eu, ei oratio audire his, eos principes scriptorem ad.',
    imageTitle_ua: '8 років',
    imageTitle_ru: '8 лет',
    imageTitle_en: '8 years',
    imageDescription_ua: 'Ми створюємо для вас \nзатишок та комфорт',
    imageDescription_ru: 'Мы создаем для вас \nуют и комфорт',
    imageDescription_en: 'We will let you \ncalm down and comfort',
  },
  home_partners: {
    description_ua: 'Наші партнери',
    description_ru: 'Наши партнеры',
    description_en: 'Our partners',
    title_ua: 'Ми раді співпрацювати з \nвідомими брендами',
    title_ru: 'Мы рады сотрудничать с \nизвестными брендами',
    title_en: 'We are happy to cooperate with \nfamous brands',
    button_ua: 'Більше про студію',
    button_ru: 'Больше о студии',
    button_en: 'More about the studio',
  },
  home_steps: {
    description_ua: 'До створення меблів \nвашої мрії',
    description_ru: 'К созданию мебели \nвашей мечты',
    description_en: 'To create the furniture of \nyour dreams',
    title_ua: '4 кроки',
    title_ru: '4 шага',
    title_en: '4 steps',
    first_ua: 'Вибір продукту та вибір \nстилю меблів',
    first_ru: 'Выбор продукта и выбор \nстиля мебели',
    first_en: 'Product selection and \nfurniture style selection',
    second_ua: 'Договір та розрахунок \nпроекту',
    second_ru: 'Договор и расчет \nпроекта',
    second_en: 'Contract and project \ncalculation',
    third_ua: 'Креслення та \nтехнологічна частина',
    third_ru: 'Чертеж и \nтехнологическая часть',
    third_en: 'Drawings and \ntechnological part',
    fourth_ua: 'Доставка та монтаж \nготових меблів',
    fourth_ru: 'Доставка и монтаж \nготовой мебели',
    fourth_en: 'Delivery and installation of \nfinished furniture',
  },
  home_galery: {
    description_ua: 'Наші останні роботи',
    description_ru: 'Наши последние работы',
    description_en: 'Our latest work',
    title_ua: 'Усі наші проекти та вироби \nстворено для вас з любов’ю',
    title_ru: 'Все наши проекты и изделия \nсозданы для вас с любовью',
    title_en: 'All our projects and products \nare created for you with love',
    catalogButton_ua: 'Перейти в каталог',
    catalogButton_ru: 'Перейти в каталог',
    catalogButton_en: 'Go to the directory',
    orderButton_ua: 'Замовити меблі зараз',
    orderButton_ru: 'Заказать мебель сейчас',
    orderButton_en: 'Order furniture now',
  },
};

